---
Title: 特定の例外が発生することを確認するユニットテスト
Category:
- java
Date: 2010-05-02T00:00:00+09:00
URL: https://kiririmode.hatenablog.jp/entry/20100502/p1
EditURL: https://blog.hatena.ne.jp/kiririmode/kiririmode.hatenablog.jp/atom/entry/8454420450078211924
---


Perl でいう dies_ok (See: [http://search.cpan.org/~adie/Test-Exception-0.29/lib/Test/Exception.pm:title])的なユニットテストだが、JUnit 4 を使ってるんだったら @Test アノテーションでできる。
-[http://kentbeck.github.com/junit/javadoc/latest/org/junit/Test.html:title]
>|java|
@Test(expected=FileNotFoundException.class)
public void testParseNotFound() throws Exception {
        String filePath = "resource/notfound.log";
        LogParser parser = new LogParser();
        parser.parse( filePath );
}
||<
@Test アノテーションはオプションで expected 要素を記述することができ、ここに記述した Throwable の子クラスがテストメソッド中で投げられたときにテストが成功となる。
他のテスト内容はメソッド中に書くのに、なんで例外だけはアノテーションでテストするんだよみたいな話はない。考えてはいけない。心を無にして悟りを開こう。
